filters:
- slug: "guitar-standard"
  # sentences or regexes should be defined
  expressions: ["guitar", "E standard"]  # match words/sentences of this list
  is_regex: false
  is_case_sensitive: false  # OPTIONAL default `false`. Tells if we must match the case.
  is_include: false  # if the article must match the filter, default it is false to exclude
  must_match_all: false  # OPTIONAL default `false`: if all defined sentences and regexes should match, default a result is valid when one of the regexes/sentences match
  filter_in_title: true  # default true
  filter_in_summary: true  # default true
  filter_in_content: false  # default false
- slug: "favorite-bands"
  expressions: ["Ghost", "Iron Maiden", "Judas Priest" ]
- slug: "unwanted-instruments"
  expressions: ["trumpet", "drum"]

groups:
- title: My group name
  output: my-group-name.xml
  filters: []
  # retention: 60  # retention in days
  feeds:
  - title: "Feed title"
    url: "https://my-favourite-website.org/rss"  # feed URL
    page_url: "https://my-favourite-website.org/"  # OPTIONAL will be matched when feed is read, useless when the feed is in a group
    xpath: ""  # OPTIONAL xpath to retrieve article content instead of brief in some feeds
    retention: 60  # retention in days
    retrieve_server_media: true  # OPTIONAL override default value
    filters: ["unwanted-instruments", "favorite-bands"]  # applied filters, order is important
